<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Platform>Any CPU</Platform>
    <AssemblyName>TweaksOfYore</AssemblyName>
    <Description>A quality of life mod for Peaks of Yore.</Description>
    <Version>0.8.0</Version>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <Configurations>Debug;Release</Configurations>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <IntermediateOutputPath>obj/$(Configuration)</IntermediateOutputPath>
    <OutputPath>bin/$(Configuration.ToLower())/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Equals('Debug'))">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Equals('Release'))">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
    <PackageReference Include="BepInEx.Core" Version="5.*"/>
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.41" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup Condition="'$(OS)' == 'Unix'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/>
  </ItemGroup>

  <Import Condition="Exists('Config.props')" Project="Config.props"/>

  <PropertyGroup Condition="'$(GamePath)' == ''">
    <GamePath Condition="'$(OS)' == 'Unix'">$(HOME)/.local/share/Steam/steamapps/common/Peaks of Yore</GamePath>
    <GamePath Condition="'$(OS)' == 'Windows_NT'">C:/Program Files (x86)/Steam/steamapps/common/Peaks of Yore</GamePath>
  </PropertyGroup>

  <PropertyGroup>
    <GameLibPath>$(GamePath)/Peaks of Yore_Data/Managed</GameLibPath>
    <PluginOutputPath>$(GamePath)/BepInEx/plugins</PluginOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp.dll">
      <HintPath>$(GameLibPath)/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="ModMenu.dll">
      <HintPath>$(PluginOutputPath)/ModMenu.dll</HintPath>
    </Reference>
    <Reference Include="UILib.dll">
      <HintPath>$(PluginOutputPath)/UILib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI.dll">
      <HintPath>$(GameLibPath)/UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyPackageAssembliesToSubFolder" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths
        Condition="'%(ReferenceCopyLocalPaths.NuGetPackageId)' != ''"
        Update="$(ReferenceCopyLocalPaths)"
        DestinationSubDirectory="libs/"/>
    </ItemGroup>
  </Target>

  <Target
    Name="GeneratePluginVersion"
    BeforeTargets="BeforeCompile">
    <WriteLinesToFile
      File="$(IntermediateOutputPath)/PluginInfo.cs"
      Lines="namespace $(RootNamespace) { internal static class PluginInfo { internal const string PLUGIN_VERSION=&quot;$(Version)&quot;%3B } }"
      Overwrite="true"/>
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)/PluginInfo.cs"/>
    </ItemGroup>
  </Target>

  <Target
    Condition="$(InstallAfterBuild) == true"
    Name="CopyBuild"
    AfterTargets="Build">
    <Copy
      SourceFiles="$(OutputPath)/$(AssemblyName).dll"
      DestinationFolder="$(PluginOutputPath)/"/>
    <Message Text="$(AssemblyName) -> $(PluginOutputPath)/$(AssemblyName).dll" Importance="High"/>
  </Target>
</Project>
<!-- vim: set et sw=2 ts=2 ft=xml: -->
